services:
  frontend:
    image: ghcr.io/tonitomc/software-frontend:latest
    container_name: software-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: ghcr.io/tonitomc/software-backend:latest
    container_name: software-backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:admin123@db:5432/oftalcrm?sslmode=disable
      - JWT_SECRET=OkM8ombEEyIkpqmIkMYg48DixlX8xthGFXmjmdw1bf8
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: minio-s3-prod
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    image: postgres:latest
    container_name: software-db-prod
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oftalcrm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oftalcrm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  minio_data:
    driver: local
